import type { Metadata } from "next";
import { Domine, Italiana } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const primary = Domine({
  variable: "--font-primary",
  subsets: ["latin"],
});

const title = Italiana({
  variable: "--font-title",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${primary.variable} ${title.variable}} antialiased`}
      >
        <div className="flex flex-col h-screen">
          <Header />
          <main className="container mx-auto max-w-7xl">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
