// import type { Metadata } from "next";
import { Playfair_Display, Merriweather } from "next/font/google";
import "./globals.css";
// import Header from "@/components/Header";
import Footer from "@/components/Footer";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: "400"
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${merriweather.variable} antialiased`}
      >
        <div className="flex flex-col h-screen">
          {/* <Header /> */}
          {/* <main className="container mx-auto max-w-7xl"> */}
          <main className="px-7">
            {children}
            <Footer />
          </main>
        </div>
      </body>
    </html>
  );
}
